language: python
sudo: false
cache:
  directories:
  - "$HOME/.pip-cache/"
env:
- TOXENV=py26 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
- TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
- TOXENV=py32 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
- TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
- TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
- TOXENV=pypy PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
- TOXENV=pypy3 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
install:
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
script:
- tox -r
after_success:
- codecov
notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: "RwQphRG0/tkWqSL96n/k00Xb7wHCmp+Zd1iM23PIWZvQhsJ06HtzlKD/3K7B6GADNNIA1hHjbJ0OzDBBeVoTjtFEovnrFuorRY1cK9YflsNT4/Is8aBstCcqLe1CXDvgRpAL7204ylDXMfUTsrA5hNEhJrXl03ZyWpAivYqKOr7cqfi8IpbTFF3d8QEYlOyRW4yQQqYHpYliteiuVJvnDSoD5AlpxDaq9nQckJEPDUTAHNXxIDzb0ObULTARIsgut/58pI8lKtw3Zw4UtpzLClbmnfSOnII0d+aY6urukHwlGwYeRlimQ2XJQuiB41cTkqAFVPtm4T7+bRE9iB3pFKOdEZv7S6eKUuHN3TLUdxkW0EWVMIhwSwhFbt+fUM8Q9z2OhoVBVELtbjpst7bmkvKmpC/zu3p8owu8xd6X2zy48ziP6nhco2U9Qq3zSdt/8MQf/62acSPknOZst8Lx8xBr6D7OkwQ5tBfNkchDrqCnp45yQ4mmOUs8Rk4DeVmoLuMpJEpMV0hBqEjNjuHe3vXEEU5Hs5cZVeISSdnX1A4ECKmr66zfDwnQUdKLCKo07Zml++UOIG8FVtgOi9jaTjzni8xs+80NC9VmhoSNzK/SboziOB/kpzNlovIGFKl33ZJgMPaaYrj7qQOgH0+QsKtmY7uoayu+N7cvv6MK0aQ="
    api_key:
      secure: "unlquBazoPcBe7AJMV2kGst6m2KmIJs9Pjg7xAt8r5c8NzFC3sK9r3OGCMFZjv82nGaqmY3dLpMnLyU5P4pqMN6r8Hjj66D8BiGdWdBoyhxa7vqkO9TI7bYEhk88SX8YiDt6f4yPap/tdgmnESCfYoNMqxAUloBJUFhsCoiMZ19BN9vogBEeC9F/GX0U0/CQ+rujiIGgUO1waIa9K79JaPDEvAoHGtOaRalsptR8dlqWK8krZ8dsAWwqpKdaEeK8Isn59qDjBx71lk9Wl6+4Xd6fG9/ncLsDUoKgmzD+3UbonBIFEAIy988Yvi8P5EEAM7ay3/YV9iaDRKnMh6HOSQpuQdfpqK5m8U2vX12KtmdYcsnPH5ChKPQXrA+Ag82QopSw2EL8iFv6ZDSY6mZCkrMkgYoFdmvF/K6IPhsnwiUghUHcpFB9HCm/xIyqxGZxF82P3SzhcW3veULySGJxHEc3XtSQ+KWWa0kpHV9NQOezkzRqoRwwmWca6m/dmRwrDX15fA/Zt3q40IRkbQZhd0TXlwLjgYSd7fN1CmxPD1OBiDOaJCVXIG1Z7GW2L4WlEhJIxk7MFzdWpIszHOxGzBRQKESGRe8OS3fJYIzeo0mLD8ErPNZ9yyMUA5PlxAmkWqB2omZhU18f5gmiEtG9UugjZWyxZJmdf8sPP4W2F8w="
branches:
  except:
  - "/^noci-.*$/"
